server:
  port: ${NOTIFICATION_PORT:8083}
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service

  # Cau hinh KAFKA
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092} # <--- Dùng biến môi trường
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: event:com.fintrack.notification_service.dto.event.NotificationEvent

  # Cau hinh EMAIL (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    # Lấy từ biến môi trường, không để lộ email/pass trong code
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}