server:
  port: 8083
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service

  # Cau hinh KAFKA
  kafka:
    bootstrap-servers: localhost:29092 # Ket noi vao port lo ra cua Docker
    consumer:
      group-id: notification-group # Ten nhom consumer
      auto-offset-reset: earliest # Doc tu tin nhan cu nhat neu bi mat ket noi
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*" # Cho phep nhan moi object JSON
        spring.json.type.mapping: event:com.fintrack.notification_service.dto.event.NotificationEvent

  # Cau hinh EMAIL (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: "haun4700@gmail.com"
    password: "hcaj ocvd ruzf szaa" # <--- Update later
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/