server:
  port: 8081 # Chay cong khac Identity (8080)
  servlet:
    context-path: /wallet # Prefix cho API: http://localhost:8081/wallet/wallets

spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_service_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Cau hinh Eureka (Service Discovery)
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 5s
        readTimeout: 5000

# Cau hinh Security
jwt:
  signerKey: "1234567890123456789012345678901234567890123456789012345678901234"

app:
  internal-secret: "bao-mat-noi-bo-123" # Phải khớp với Gateway