server:
  port: 8081 # Chay cong khac Identity (8080)
  servlet:
    context-path: /wallet # Prefix cho API: http://localhost:8081/wallet/wallets

spring:
  application:
    name: wallet-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/wallet_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      # Đổi tên group để bỏ qua message lỗi cũ
      group-id: wallet-service-group-v2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

# Cau hinh Eureka (Service Discovery)
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 5s
        readTimeout: 5000

# Cau hinh Security
jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  internal-secret: ${INTERNAL_SECRET}