server:
  port: 8761 # Cong chuan quoc te cua Eureka

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false # Vi minh la Server, khong can dang ky voi ai
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5 # Giup khoi dong nhanh hon khi dev