version: '3.8'

services:
  # Database cho Service Identity (Quản lý User)
  identity-db:
    image: postgres:16-alpine
    container_name: fintrack-identity-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=identity_service_db
    ports:
      - "5432:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  wallet-db:
    image: postgres:16-alpine
    container_name: fintrack-wallet-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_service_db
    ports:
      - "5433:5432"
    volumes:
      - wallet_data:/var/lib/postgresql/data

  transaction-db:
    image: postgres:16-alpine
    container_name: fintrack-transaction-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transaction_service_db
    ports:
      - "5434:5432"
    volumes:
      - transaction_data:/var/lib/postgresql/data

  # --- TOOLS ---
  # 1. Công cụ quản lý DB (pgAdmin) - Optional nhưng nên có để dễ debug
  pgadmin:
    image: dpage/pgadmin4
    container_name: fintrack-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fintrack.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - identity-db
      - wallet-db
      - transaction-db

  # --- MESSAGE BROKER (KAFKA) ---

  # 1. Zookeeper (Quản lý Kafka Cluster)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: fintrack-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. Kafka Broker (Nơi chứa tin nhắn)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: fintrack-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092" # Port cho Spring Boot (Host) kết nối vào
      - "9092:9092"   # Port nội bộ
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình để Kafka biết đường trả lời khi được gọi từ bên ngoài (localhost) và bên trong (docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  identity_data:
  wallet_data:
  pgadmin_data:
  transaction_data: