server:
  port: 8080 # Service n�y s? ch?y ? c?ng 8080
  servlet:
    context-path: /identity # Thêm dòng này: Tự động thêm /identity vào trước mọi API

spring:
  application:
    name: identity-service

  # C?u h�nh k?t n?i Database (Tr? v�o c�i Docker b?n v?a d?ng)
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # C?u h�nh JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update # T? ??ng t?o b?ng d?a tr�n code Java (Entity)
    show-sql: true # Hi?n c�u l?nh SQL trong log ?? d? debug
    properties:
      hibernate:
        format_sql: true # Format SQL cho ??p
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1234567890123456789012345678901234567890123456789012345678901234" # 64 digits - Key này phải ĐỦ DÀI (ít nhất 32 ký tự) nếu không sẽ lỗi