server:
  port: 8080 # Service nay se chay o cong 8080
  servlet:
    context-path: /identity # Them dong nay: Tu dong thêm /identity vao truoc moi API

spring:
  application:
    name: identity-service

  # Cau hinh ket noi Database
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # Cau hinh JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1234567890123456789012345678901234567890123456789012345678901234" # 64 digits - Key nay phai DU DAI (it nhat 32 ky tu) neu khong se loi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/