server:
  port: 8082 # Identity: 8080, Wallet: 8081, Transaction: 8082
  servlet:
    context-path: /transaction # Base path

spring:
  application:
    name: transaction-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/transaction_service_db}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ĐÃ XÓA spring.json.type.mapping Ở ĐÂY
    consumer:
      group-id: transaction-service-group-v2

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            # Dùng bản Flash cho tốc độ siêu nhanh và rẻ (chuyên đọc ảnh)
            model: gemini-2.5-flash
            # Nhiệt độ (0.0 đến 1.0) -> Set 0.2 để AI trả lời chuẩn xác logic JSON, không sáng tạo chém gió
            temperature: 0.2

# Cau hinh Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

# Cau hinh Feign Client (de goi Wallet Service)
feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 5s
        readTimeout: 5000

# Cau hinh Security
jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  internal-secret: ${INTERNAL_SECRET}
  exchange-rate:
    url: https://open.er-api.com/v6
    # Đã xóa dòng api-key cho nhẹ nợ