server:
  port: 8888 # Cong chuan cua Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: lb://IDENTITY-SERVICE # lb = Load Balancer, IDENTITY-SERVICE = ten spring.application.name ben kia
              predicates:
                - Path=/identity/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true