server:
  port: 8888 # Cong chuan cua Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ----------------------------------------------------
            # 1. Route Public (Ưu tiên chạy trước)
            # Khớp: /identity/auth/login, /identity/auth/token...
            # ----------------------------------------------------
            - id: identity_public
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/identity/auth/**
              # Không có filters -> Ai vào cũng được

            # ----------------------------------------------------
            # 2. Route Private (Hốt tất cả những gì còn lại)
            # Khớp: /identity/users, /identity/admin, /identity/bat-ky-cai-gi...
            # ----------------------------------------------------
            - id: identity_private
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/identity/** # <--- Bắt tất cả prefix /identity
              filters:
                - Authentication # <--- Bắt buộc phải có token mới cho qua

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true